version: '3.9'
services:
  #  See https://medium.com/ms-sql-server-containers/create-and-setup-ms-sql-server-database-docker-containers-2422f757464d
  # database name=master
  # schema=dbo
  # user=sa
  # password=Pass@word
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    command: /bin/bash ./entrypoint.sh
    ports:
      - "1433:1433"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./setup_database.sh:/setup_database.sh
      - ./initial-data.sql:/initial-data.sql
