# https://medium.com/@chameerarupasinghe/spring-boot-hibernate-with-microsoft-sql-server-dbdb550bb9dd

docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" \
   -p 1433:1433 --name mssql-container --hostname sql1 \
   -d \
   mcr.microsoft.com/mssql/server:2022-latest