# https://medium.com/@chameerarupasinghe/spring-boot-hibernate-with-microsoft-sql-server-dbdb550bb9dd
docker run --cap-add SYS_PTRACE -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=yourStrong(!)Password' \
-p 1433:1433 --name mssql-container \
-d mcr.microsoft.com/azure-sql-edge